name: vjti
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  #  sdk: ">=2.18.6 <3.0.0"
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  firebase_core: ^2.7.0
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  flutter_rating_bar: ^4.0.1
  gender_picker: ^1.1.0
  intl_phone_number_input: ^0.7.2
  flutter_sound: ^9.2.13
  path_provider: ^2.0.13
  permission_handler: ^9.0.0
  permission_handler_android: ^9.0.2+1
  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.0.18
  international_phone_number: ^0.0.1
  url_launcher: ^6.1.10
  image_picker: ^0.8.6+3
  video_player: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Fonts/
    - assets/Images/
    - assets/Specialisation/
    - assets/OnlineMedication/
    - assets/Hospital/

  fonts:
    - family: AppName
      fonts:
        - asset: assets/Fonts/Lobster-Regular.ttf
          weight: 600
