// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_7bmYDOdEaqHXgZvZ3qS2tofWmbmSvo',
    appId: '1:732529033042:web:50a24acea30e32743fc48b',
    messagingSenderId: '732529033042',
    projectId: 'aarogyagram',
    authDomain: 'aarogyagram.firebaseapp.com',
    storageBucket: 'aarogyagram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArPtGtxRSBK7pS4EqCB2fhY1fkHiqu8cs',
    appId: '1:732529033042:android:e2e60c3382dac0223fc48b',
    messagingSenderId: '732529033042',
    projectId: 'aarogyagram',
    storageBucket: 'aarogyagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJyoPjNiwHdXG38pYFd-CIkMtkIRpK_E',
    appId: '1:732529033042:ios:dbf5de82f3ad6fd43fc48b',
    messagingSenderId: '732529033042',
    projectId: 'aarogyagram',
    storageBucket: 'aarogyagram.appspot.com',
    iosClientId: '732529033042-q8cdb73srltb1855n4k49tjkorl6efeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.vjti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJyoPjNiwHdXG38pYFd-CIkMtkIRpK_E',
    appId: '1:732529033042:ios:dbf5de82f3ad6fd43fc48b',
    messagingSenderId: '732529033042',
    projectId: 'aarogyagram',
    storageBucket: 'aarogyagram.appspot.com',
    iosClientId: '732529033042-q8cdb73srltb1855n4k49tjkorl6efeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.vjti',
  );
}
